version: '3'

services:
  node_server:
    # image: node:21.6.2-bullseye
    build: 
      context: .
      dockerfile: dockerfileFront
    container_name: nextjs_uidemo
    user: node
    working_dir: /app
    volumes:
      - type: bind
        source: ./app
        target: /app
      # - type: bind
      #   source: /var/run/docker.sock
      #   target: /var/run/docker.sock
    ports:
      - "3180:3000"
    tty: true
  
  node_api_server:
    build:
      context: .
      dockerfile: dockerfileBack
    container_name: express_apiserver
    user: node
    working_dir: /app
    volumes:
      - type: bind
        source: ./api
        target: /app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    tty: true